## Vectors

In [4]:
# asssigning to x
x = [1, 2, 3, 4, 5]

In [3]:
# Getting output
x

[1, 2, 3, 4, 5]

In [5]:
#importing library
import numpy as np
x = np.array([1, 2, 3, 4, 5])

In [6]:
print(x)

[1 2 3 4 5]


In [8]:
#getting type of x
print(type(x))

<class 'numpy.ndarray'>


## Matrix

In [9]:
m = np.array([[1, 5, 2], [4, 7, 4], [2, 0, 9]])

In [12]:
# viewing the values of matrix
print(m)

[[1 5 2]
 [4 7 4]
 [2 0 9]]


In [13]:
#View shape
print(m.shape)

(3, 3)


In [14]:
# matrix transpose
print('Matrix Transpose:\n', m.transpose(), '\n')

Matrix Transpose:
 [[1 4 2]
 [5 7 0]
 [2 4 9]] 



In [15]:
# matrix determinant
print ('Matrix Determinant:', np.linalg.det(m), '\n')

Matrix Determinant: -105.00000000000006 



In [16]:
# inversing the matrix
m_inv = np.linalg.inv(m)
print ('Matrix inverse:\n', m_inv, '\n')

Matrix inverse:
 [[-0.6         0.42857143 -0.05714286]
 [ 0.26666667 -0.04761905 -0.03809524]
 [ 0.13333333 -0.0952381   0.12380952]] 



In [17]:
# identity matrix (result of matrix x matrix_inverse)
iden_m = np.dot(m, m_inv)
iden_m = np.round(np.abs(iden_m), 0)
print ('Product of matrix and its inverse:\n', iden_m)

Product of matrix and its inverse:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Eigen Decomposition

In [18]:
# eigendecomposition
m = np.array([[1, 5, 2],
[4, 7, 4],
[2, 0, 9]])

eigen_vals, eigen_vecs = np.linalg.eig(m)
print('Eigen Values:', eigen_vals, '\n')
print('Eigen Vectors:\n', eigen_vecs)

Eigen Values: [-1.32455532 11.32455532  7.        ] 

Eigen Vectors:
 [[-0.91761521  0.46120352 -0.46829291]
 [ 0.35550789  0.79362022 -0.74926865]
 [ 0.17775394  0.39681011  0.46829291]]


## Singular Value Decomposition

In [19]:
# Singular Value Decomposition
m = np.array([[1, 5, 2],
[4, 7, 4],
[2, 0, 9]])

U, S, VT = np.linalg.svd(m)
print('Getting SVD outputs:-\n')
print('U:\n', U, '\n')
print('S:\n', S, '\n')
print('VT:\n', VT, '\n')

Getting SVD outputs:-

U:
 [[ 0.3831556  -0.39279153  0.83600634]
 [ 0.68811254 -0.48239977 -0.54202545]
 [ 0.61619228  0.78294653  0.0854506 ]] 

S:
 [12.10668383  6.91783499  1.25370079] 

VT:
 [[ 0.36079164  0.55610321  0.74871798]
 [-0.10935467 -0.7720271   0.62611158]
 [-0.92621323  0.30777163  0.21772844]] 



## Statistics

# Descriptive Statistics

In [20]:
# importing scipy library to get the descriptive statistics
import scipy as sp
import scipy.stats
import numpy as np

# get data
nums = np.random.randint(1,20, size=(1,15))[0]
print('Data: ', nums)

Data:  [19 10  5  1  9  9 14  1  8 12 18 17  1 14  8]


In [21]:
#get descriptive stats
print ('Mean:', sp.mean(nums))

Mean: 9.733333333333333


In [22]:
#get descriptive stats
print ('Mean:', sp.mean(nums))

Mean: 9.733333333333333


In [23]:
#view mode value of the data
print ('Mode:', sp.stats.mode(nums))

Mode: ModeResult(mode=array([1]), count=array([3]))


In [24]:
#view standard deviation value of the data
print ('Standard Deviation:', sp.std(nums))

Standard Deviation: 5.813394495091105


In [25]:
#view variance value of the data
print ('Variance:', sp.var(nums))

Variance: 33.79555555555556


In [26]:
#view skew value of the data
print ('Skew:', sp.stats.skew(nums))

Skew: -0.06928016624207455


In [27]:
#view Kurtosis value of the data
print ('Kurtosis:', sp.stats.kurtosis(nums))

Kurtosis: -1.044964429419329


In [28]:
import pandas as pd
# turning off the warning messages
pd.options.mode.chained_assignment = None # default='warn'
# get data
df = pd.read_csv('C:\\Users\\SOURABH\\Desktop\\student_records.csv')
df

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No
5   Simon            A        Y             92            79       Yes
6  Robert            B        Y             60            59        No
7   Trent            C        Y             75            33        No

## Data Preparation, Feature Extraction & Engineering

In [29]:
# get features and corresponding outcomes
feature_names = ['OverallGrade', 'Obedient', 'ResearchScore',
'ProjectScore']
training_features = df[feature_names]
outcome_name = ['Recommend']
outcome_labels = df[outcome_name]

In [30]:
# view features
training_features

OverallGrade Obedient  ResearchScore  ProjectScore
0            A        Y             90            85
1            C        N             85            51
2            F        N             10            17
3            B        Y             75            71
4            E        N             20            30
5            A        Y             92            79
6            B        Y             60            59
7            C        Y             75            33

In [31]:
#View Outcome Lables
outcome_labels

Recommend
0       Yes
1       Yes
2        No
3        No
4        No
5       Yes
6        No
7        No

In [32]:
# list down features based on type
numeric_feature_names = ['ResearchScore', 'ProjectScore']
categoricial_feature_names = ['OverallGrade', 'Obedient']

In [47]:
#importing scikit learn for preprocessing
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [49]:
# fit scaler on numeric features
ss.fit(training_features[numeric_feature_names])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [51]:
# scale numeric features now
training_features[numeric_feature_names] = ss.transform(training_features[numeric_feature_names])

In [52]:
# view updated featureset
training_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_B  \
0       0.899583      1.376650               1               0   
1       0.730648     -0.091777               0               0   
2      -1.803390     -1.560203               0               0   
3       0.392776      0.772004               0               1   
4      -1.465519     -0.998746               0               0   
5       0.967158      1.117516               1               0   
6      -0.114032      0.253735               0               1   
7       0.392776     -0.869179               0               0   

   OverallGrade_C  OverallGrade_E  OverallGrade_F  Obedient_N  Obedient_Y  
0               0               0               0           0           1  
1               1               0               0           1           0  
2               0               0               1           1           0  
3               0               0               0           0           1  
4               0               1               0           1           0  
5               0               0               0           0           1  
6               0               0               0           0           1  
7               1               0               0           0           1

In [55]:
training_features = pd.get_dummies(training_features, columns = categoricial_feature_names)
# view newly engineering features
training_features

KeyError: "None of [Index(['OverallGrade', 'Obedient'], dtype='object')] are in the [columns]"

## Modeling

In [56]:
#get list of new categorical features
categorical_engineered_features = list(set(training_features.columns) - set(numeric_feature_names))

In [57]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [58]:
# fit the model
lr = LogisticRegression()
model = lr.fit(training_features,
np.array(outcome_labels['Recommend']))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [59]:
# view model parameters
model
Out[9]: LogisticRegression(C=1.0, class_weight=None, dual=False,
fit_intercept=True, intercept_scaling=1, max_iter=100,
multi_class='ovr', n_jobs=1, penalty='l2',
random_state=None, solver='liblinear', tol=0.0001,
verbose=0, warm_start=False)

## Model Evaluation

In [60]:
# simple evaluation on training data
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['Recommend'])

In [61]:
# evaluate model performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print('Accuracy:', float(accuracy_score(actual_labels,
pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))

Accuracy: 100.0 %
Classification Stats:
              precision    recall  f1-score   support

          No       1.00      1.00      1.00         5
         Yes       1.00      1.00      1.00         3

   micro avg       1.00      1.00      1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



## Model Deployment

In [62]:
from sklearn.externals import joblib
import os

In [63]:
# save models to be deployed on your server
if not os.path.exists('Model'): os.mkdir('Model')
if not os.path.exists('Scaler'): os.mkdir('Scaler')
joblib.dump(model, r'Model/model.pickle')
joblib.dump(ss, r'Scaler/scaler.pickle')

['Scaler/scaler.pickle']

## Prediction in Action

In [64]:
# load model and scaler objects
model = joblib.load(r'Model/model.pickle')
scaler = joblib.load(r'Scaler/scaler.pickle')

In [65]:
## data retrieval
new_data = pd.DataFrame([{'Name': 'Nathan', 'OverallGrade': 'F',
'Obedient': 'N', 'ResearchScore': 30, 'ProjectScore': 20}, {'Name': 'Thomas', 'OverallGrade': 'A',
'Obedient': 'Y', 'ResearchScore': 78, 'ProjectScore': 80}])
new_data = new_data[['Name', 'OverallGrade', 'Obedient', 'ResearchScore', 'ProjectScore']]
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore
0  Nathan            F        N             30            20
1  Thomas            A        Y             78            80

In [66]:
## data preparation
prediction_features = new_data[feature_names]

In [67]:
# scaling
prediction_features[numeric_feature_names] = scaler.transform(prediction_features[numeric_feature_names])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  


In [68]:
# engineering categorical variables
prediction_features = pd.get_dummies(prediction_features,
columns=categoricial_feature_names)

In [69]:
# view feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0           30.0          20.0               0               1           1   
1           78.0          80.0               1               0           0   

   Obedient_Y  
0           0  
1           1

In [70]:
# add missing categorical feature columns
current_categorical_engineered_features = set(prediction_features.columns) - set(numeric_feature_names)
missing_features = set(categorical_engineered_features) - current_categorical_engineered_features
# add zeros since feature is absent in these data samples
for feature in missing_features:prediction_features[feature] = [0] * len(prediction_features)
# view final feature set
prediction_features

ResearchScore  ProjectScore  OverallGrade_A  OverallGrade_F  Obedient_N  \
0           30.0          20.0               0               1           1   
1           78.0          80.0               1               0           0   

   Obedient_Y  OverallGrade_B  OverallGrade_C  OverallGrade_E  
0           0               0               0               0  
1           1               0               0               0

In [72]:
# predict using model
predictions = model.predict(prediction_features)

In [73]:
## display results
new_data['Recommend'] = predictions
new_data

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0  Nathan            F        N             30            20       Yes
1  Thomas            A        Y             78            80       Yes